sonar.projectKey=josekero_beer_designer
sonar.organization=josekero
sonar.sourceEncoding=UTF-8
sonar.sources=src/app,backend/src/main
sonar.tests=src/app
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/beer-project/lcov.info
sonar.java.binaries=backend/target/classes
